version: '3'
services:
  db:
    # platform: linux/arm64
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    # ports:
    #   - ${DB_PORT}:3306
    # command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/mpass_index_app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - 'db'
      - chromium
  chromium:
    image: seleniarm/standalone-chromium # M1対応イメージ
    volumes:
    - ./tmp/downloads:/usr/src/mpass_index_app/tmp/downloads
    ports:
      - 4444:4444
volumes:
  mysql-data:
    driver: local
