version: '3'
services:
  db:
    # platform: linux/arm64
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # - MYSQL_DATABASE=${DB_NAME}
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    # ports:
    #   - ${DB_PORT}:3306
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/mpass_index_app
    ports:
      - '3000:3000'
    # environment:
    #   - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - 'db'
volumes:
  mysql-data:
    driver: local
